name: Master

on:
  push:
    branches:
      - 'master'

jobs:
  test-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
    - run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NACS_BUILDER_CI_TOKEN }}
    - name: Run test with Node.js ${{ matrix.node-version }}
      run: npm run test
   test-karma:
     runs-on: ubuntu-latest
     timeout-minutes: 10
     strategy:
       matrix:
         node-version: [14.x]
     steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
     - run: npm install
     - name: Run karma tests
       run: npm run test-karma
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
    - run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NACS_BUILDER_CI_TOKEN }}
    - name: Run eslint
      run: npm run lint

